<?php
/**
 * @file
 * .module file of Tripal Fancy Fields.
 */

use Drupal\Core\Url;

/**
 * Implements hook_theme().
 * Used by Tripal Fancy Fields Configure Fields.
 *
 * @see templates in /templates
 */
function trpfancy_fields_theme($existing, $type, $theme, $path) {
  $context_links = [
    'configure_dataid' => ['form' => 'tripal_fancyfields.configure_data_id']
  ];
  
  $link = Url::fromRoute($context_links['configure_dataid']['form']);
  $links_ui[ 'configure_dataid' ] = \Drupal::l(t('Configure'), $link);

  $variables = [
    // Tripal Fancy Fields Configure Fields Page.
    'theme-tripal-fancyfields-configure' => [
      'variables' => [
        'context_links' => $links_ui
      ],
      'template'  => 'template-tripal-fancyfields-configure',
    ],
  ];

  return $variables;
}